apiVersion: v1
baseDomain: ocp.lab
metadata:
  name: paas

compute:
- name: worker
  replicas: 2

controlPlane:
  name: master
  replicas: 3

platform:
  none: {}

networking:
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: 192.168.0.0/24
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMzc0NDc1MzZlMjUxNDA2NDk3ODg2OTIyZDk1MTM0YTc6SENYU1dFTEpCUlBLRU1ORVlNVFhHREZCMTQxR1QwV0VYT0xFTTRMTlhGVDE2UjhLVFJTRkQ5QktETEpMVEM5RA==","email":"jinsae84@naver.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMzc0NDc1MzZlMjUxNDA2NDk3ODg2OTIyZDk1MTM0YTc6SENYU1dFTEpCUlBLRU1ORVlNVFhHREZCMTQxR1QwV0VYT0xFTTRMTlhGVDE2UjhLVFJTRkQ5QktETEpMVEM5RA==","email":"jinsae84@naver.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTQ3NTE0MmEwLTAwZWQtNGVkNy1hZjI4LWNiNDc3NGM5N2FmMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTROR0V3TlROaE5ETXhNalEwTkRCa1lqWm1ZVEF6WmpGa016VTRaV05pWlNKOS5HYjlsQnV6R05SYXd3UGpQOTlFaGdqY0tTNGtaRC1EN2FLMklmLUpjZkhrSk1nOVpkYW5kTlJzcHhJaTBqakdaaFVFU0FtdzI2NVlVSWhSUk9SaEhGenllX1FOVkw0SEJLRkcyUGo5RFZiTXhjejBTNF95OFdJeGtacUp6dVJ6cU81aXlvT0xCZVBIRVY0N3RvaGRzRXVOaW15OHRNMktiSzVjOFFPNm1uT0h3dHBOUEhGVTUzUXRzcmw1ZWthTDBpaVdHSjVBZ0ZlcHduQzFFUDl0bm9FZFUxMDV4enlrXzRRdGpJZFRHbmN1amZqam1kRDFSR3UyeHBkendBNTZlS28wMHNob3VMYnJGdlJlUVk1RFNaY1h0RFpNdy1ybXlodXRIWldGazhDWFJOZm9ldW5QZmdqTS0xdGQtN18zd1JfaEd6ZENBTGZDZ0tNamFuTFR5NGEwWFQ3SUtHLXB3WHJDTTF1WHY4MUJxT0V3a19aRGEzVUtmdXphaEtHbDJsTnFoRll2T09UX1RFMVRFQ09wM09fMy0zeC0xcDB6QjNMdEQ0ZmE0LUlVZzRDV18tMXQ3UGVfclh3TG9hcVJFdTFjSmxnN2pGZzc5c1FUeE1rb0VLTF84YnFzaUNrMkN2QU5nODRjWHliZ01CRHhFRDd0UkpxQ1FEQjFQMmhKYnFlLVM0cjdBeHpTZjNnbEY0cUxhTXpsZXQ1cWFzakJzY1VCaTQzay1lM1doLTdRSU44VkpSTG51TjI0SWJzWkFVWXNpVm1vcm1rN05vY0ZEZWxOWm1vemZQc0ZMYk45UDU2a29xQkQwREtfbDVqRUZqVEJfRWV1SHdONFB5Q2FWRHVQSXJyOEJHQzUxZWJqMHVhR084ZEc5Z19FVmJyekk0YjBrTTR3TUExOA==","email":"jinsae84@naver.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTQ3NTE0MmEwLTAwZWQtNGVkNy1hZjI4LWNiNDc3NGM5N2FmMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTROR0V3TlROaE5ETXhNalEwTkRCa1lqWm1ZVEF6WmpGa016VTRaV05pWlNKOS5HYjlsQnV6R05SYXd3UGpQOTlFaGdqY0tTNGtaRC1EN2FLMklmLUpjZkhrSk1nOVpkYW5kTlJzcHhJaTBqakdaaFVFU0FtdzI2NVlVSWhSUk9SaEhGenllX1FOVkw0SEJLRkcyUGo5RFZiTXhjejBTNF95OFdJeGtacUp6dVJ6cU81aXlvT0xCZVBIRVY0N3RvaGRzRXVOaW15OHRNMktiSzVjOFFPNm1uT0h3dHBOUEhGVTUzUXRzcmw1ZWthTDBpaVdHSjVBZ0ZlcHduQzFFUDl0bm9FZFUxMDV4enlrXzRRdGpJZFRHbmN1amZqam1kRDFSR3UyeHBkendBNTZlS28wMHNob3VMYnJGdlJlUVk1RFNaY1h0RFpNdy1ybXlodXRIWldGazhDWFJOZm9ldW5QZmdqTS0xdGQtN18zd1JfaEd6ZENBTGZDZ0tNamFuTFR5NGEwWFQ3SUtHLXB3WHJDTTF1WHY4MUJxT0V3a19aRGEzVUtmdXphaEtHbDJsTnFoRll2T09UX1RFMVRFQ09wM09fMy0zeC0xcDB6QjNMdEQ0ZmE0LUlVZzRDV18tMXQ3UGVfclh3TG9hcVJFdTFjSmxnN2pGZzc5c1FUeE1rb0VLTF84YnFzaUNrMkN2QU5nODRjWHliZ01CRHhFRDd0UkpxQ1FEQjFQMmhKYnFlLVM0cjdBeHpTZjNnbEY0cUxhTXpsZXQ1cWFzakJzY1VCaTQzay1lM1doLTdRSU44VkpSTG51TjI0SWJzWkFVWXNpVm1vcm1rN05vY0ZEZWxOWm1vemZQc0ZMYk45UDU2a29xQkQwREtfbDVqRUZqVEJfRWV1SHdONFB5Q2FWRHVQSXJyOEJHQzUxZWJqMHVhR084ZEc5Z19FVmJyekk0YjBrTTR3TUExOA==","email":"jinsae84@naver.com"},"bastion.ocp.lab:8443":{"auth":"YWRtaW46UGFzc3cwcmQ="}}}'

sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBYSxOuQnppsme2Rul4CxlzFLYvN6xm88XbqebrghdEO jinsae84@naver.com'

additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIE/zCCAuegAwIBAgIUW7VRtVufzfrU49m4av0CEANh2eYwDQYJKoZIhvcNAQEL
  BQAwGjEYMBYGA1UEAwwPYmFzdGlvbi5vY3AubGFiMB4XDTI2MDUyNjIwMTkwNVoX
  DTM2MDUyMzIwMTkwNVowGjEYMBYGA1UEAwwPYmFzdGlvbi5vY3AubGFiMIICIjAN
  BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv5ZC/P4OXePN03IdBC90f3GkKu7g
  qijej9VEma6RDSC5fAkKY1cRoWM8bQjZUGXAgYlPaZgU9g+pAyWqfebYhxZp/u/R
  /RiJO2QtLiV+8bnQZ/HuvHzfPUl5WA1kOrsyHdBfPWuA1aYHpzBrdoO9H11vkdX8
  Pc+Hoa6LjLVwvYmWbH+LfkLwZzZTBWloJe6+oFRgfPJO0JrJ13NNf0WUDquKkyx2
  E7Sed84GYbH9rdK3fn0ETZNimLXMHaV47aDS4Yr2a/UnJxoNlArgnoNE+HptfTaw
  N5+KN/mrzw+6t72FkW9gfvL62mbWYw6QO/8MeOmeCoNm3s4wcpHE2GS7wwwUae+o
  62geC0hy+PG7vf1wrBrv2QTwkDwoOYzItPfa9ZDMuW6KFGcpbDXCfIs8a4skd8rW
  pMeof/sHQ51E+9cYW2XP2XUWOLZOJNIV7cVBGalj3Gk6lpRd+EFO2DQFzbx0JKOQ
  ddTFkCsJp/MNjUugo4KfUwqtlFH0JjQYzb775WiuEnC7phO9aiVk9IMh71U10X6+
  znyTNPU2bDNCaQkaOrS/f0YOjB3bdBXqIxmmjvpWARcNCFAS1MOSEnyiWM1sr7PR
  T3Yl3VZVznCN9HvT9zqBi/QSRbtwGXkiZ9EtXjip8WebodFvowflN9m3//vsg3C6
  vuPZuCFomKtydmECAwEAAaM9MDswGgYDVR0RBBMwEYIPYmFzdGlvbi5vY3AubGFi
  MB0GA1UdDgQWBBT2JbeG6O/nS0UJZtEMf+wwCPm+tTANBgkqhkiG9w0BAQsFAAOC
  AgEAtClP+joFSYRMn8hfcSYEZdCNtE+YYrX29RlWh7swCP3XFMSwsgMgv6/lfrig
  MXciG62JRfkWLI+PKYWgz52P5r/gYdVsqwD+GYonazfqsv9mkatY9EN0eROwBGbu
  W+jD/s4gHaa/b2ypqkBx39minF2CGwDLmUWVgwoqY7/Fixw+w4URjBocbVQxFuw2
  +ke937RbtxYRfFec8YakgmPUokXUGd0h3Ox9CL/26eIdLEmq9UC5L2+ZvT1cdCBH
  A+TNekeKzzZGXEUnf4mis8B8yDjF9LZKmKX0b40b2an7ltD0XZkwIi41P+FzrR15
  qJKNdHehBFG7zgx6MFhD6NgNxwp5CjWOgMEkifN7ATDfsndgpFn6W/frKclBZxW9
  6AMjd7kfX4MrPIONr+fKdXYSy1VjyAtOLVVY/btScRo9EkH8bfLZHolPtVARa5dj
  ggnJbRg3Ll1+bJtnt33O3yYG04SOnJ6bgVQozOhCXOficB8/sGpiqh41h6dqDRiM
  wKaAMfjazyBVzdXbSkJ7C2TTRDtFIOmymFCyT8Rr8nMDntojpTvENKkRUwtWe7he
  inu2tmwdE5Im7IDnyX92f+p5hjRjDYs3QF0UESEakwU0W4OAU1GWFsi4tu4Yp/zQ
  4gpIo3fM9WnPhFONgCrWJFmLUnHDhLXPi0mbN2hjhCcgwZg=
  -----END CERTIFICATE-----
