apiVersion: v1
baseDomain: ocp.lab

metadata:
  name: ocp

compute:
- name: worker
  replicas: 2

controlPlane:
  name: master
  replicas: 3

networking:
  networkType: OVNKubernetes

  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23

  serviceNetwork:
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMzc0NDc1MzZlMjUxNDA2NDk3ODg2OTIyZDk1MTM0YTc6SENYU1dFTEpCUlBLRU1ORVlNVFhHREZCMTQxR1QwV0VYT0xFTTRMTlhGVDE2UjhLVFJTRkQ5QktETEpMVEM5RA==","email":"jinsae84@naver.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMzc0NDc1MzZlMjUxNDA2NDk3ODg2OTIyZDk1MTM0YTc6SENYU1dFTEpCUlBLRU1ORVlNVFhHREZCMTQxR1QwV0VYT0xFTTRMTlhGVDE2UjhLVFJTRkQ5QktETEpMVEM5RA==","email":"jinsae84@naver.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTQ3NTE0MmEwLTAwZWQtNGVkNy1hZjI4LWNiNDc3NGM5N2FmMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTROR0V3TlROaE5ETXhNalEwTkRCa1lqWm1ZVEF6WmpGa016VTRaV05pWlNKOS5HYjlsQnV6R05SYXd3UGpQOTlFaGdqY0tTNGtaRC1EN2FLMklmLUpjZkhrSk1nOVpkYW5kTlJzcHhJaTBqakdaaFVFU0FtdzI2NVlVSWhSUk9SaEhGenllX1FOVkw0SEJLRkcyUGo5RFZiTXhjejBTNF95OFdJeGtacUp6dVJ6cU81aXlvT0xCZVBIRVY0N3RvaGRzRXVOaW15OHRNMktiSzVjOFFPNm1uT0h3dHBOUEhGVTUzUXRzcmw1ZWthTDBpaVdHSjVBZ0ZlcHduQzFFUDl0bm9FZFUxMDV4enlrXzRRdGpJZFRHbmN1amZqam1kRDFSR3UyeHBkendBNTZlS28wMHNob3VMYnJGdlJlUVk1RFNaY1h0RFpNdy1ybXlodXRIWldGazhDWFJOZm9ldW5QZmdqTS0xdGQtN18zd1JfaEd6ZENBTGZDZ0tNamFuTFR5NGEwWFQ3SUtHLXB3WHJDTTF1WHY4MUJxT0V3a19aRGEzVUtmdXphaEtHbDJsTnFoRll2T09UX1RFMVRFQ09wM09fMy0zeC0xcDB6QjNMdEQ0ZmE0LUlVZzRDV18tMXQ3UGVfclh3TG9hcVJFdTFjSmxnN2pGZzc5c1FUeE1rb0VLTF84YnFzaUNrMkN2QU5nODRjWHliZ01CRHhFRDd0UkpxQ1FEQjFQMmhKYnFlLVM0cjdBeHpTZjNnbEY0cUxhTXpsZXQ1cWFzakJzY1VCaTQzay1lM1doLTdRSU44VkpSTG51TjI0SWJzWkFVWXNpVm1vcm1rN05vY0ZEZWxOWm1vemZQc0ZMYk45UDU2a29xQkQwREtfbDVqRUZqVEJfRWV1SHdONFB5Q2FWRHVQSXJyOEJHQzUxZWJqMHVhR084ZEc5Z19FVmJyekk0YjBrTTR3TUExOA==","email":"jinsae84@naver.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTQ3NTE0MmEwLTAwZWQtNGVkNy1hZjI4LWNiNDc3NGM5N2FmMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTROR0V3TlROaE5ETXhNalEwTkRCa1lqWm1ZVEF6WmpGa016VTRaV05pWlNKOS5HYjlsQnV6R05SYXd3UGpQOTlFaGdqY0tTNGtaRC1EN2FLMklmLUpjZkhrSk1nOVpkYW5kTlJzcHhJaTBqakdaaFVFU0FtdzI2NVlVSWhSUk9SaEhGenllX1FOVkw0SEJLRkcyUGo5RFZiTXhjejBTNF95OFdJeGtacUp6dVJ6cU81aXlvT0xCZVBIRVY0N3RvaGRzRXVOaW15OHRNMktiSzVjOFFPNm1uT0h3dHBOUEhGVTUzUXRzcmw1ZWthTDBpaVdHSjVBZ0ZlcHduQzFFUDl0bm9FZFUxMDV4enlrXzRRdGpJZFRHbmN1amZqam1kRDFSR3UyeHBkendBNTZlS28wMHNob3VMYnJGdlJlUVk1RFNaY1h0RFpNdy1ybXlodXRIWldGazhDWFJOZm9ldW5QZmdqTS0xdGQtN18zd1JfaEd6ZENBTGZDZ0tNamFuTFR5NGEwWFQ3SUtHLXB3WHJDTTF1WHY4MUJxT0V3a19aRGEzVUtmdXphaEtHbDJsTnFoRll2T09UX1RFMVRFQ09wM09fMy0zeC0xcDB6QjNMdEQ0ZmE0LUlVZzRDV18tMXQ3UGVfclh3TG9hcVJFdTFjSmxnN2pGZzc5c1FUeE1rb0VLTF84YnFzaUNrMkN2QU5nODRjWHliZ01CRHhFRDd0UkpxQ1FEQjFQMmhKYnFlLVM0cjdBeHpTZjNnbEY0cUxhTXpsZXQ1cWFzakJzY1VCaTQzay1lM1doLTdRSU44VkpSTG51TjI0SWJzWkFVWXNpVm1vcm1rN05vY0ZEZWxOWm1vemZQc0ZMYk45UDU2a29xQkQwREtfbDVqRUZqVEJfRWV1SHdONFB5Q2FWRHVQSXJyOEJHQzUxZWJqMHVhR084ZEc5Z19FVmJyekk0YjBrTTR3TUExOA==","email":"jinsae84@naver.com"}}}'

sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBYSxOuQnppsme2Rul4CxlzFLYvN6xm88XbqebrghdEO jinsae84@naver.com
